apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deploy
  namespace: app-ns
spec:
  selector:
    matchLabels:
      app: srv
  template:
    metadata:
      labels:
        app: srv
    spec:
      containers:
        - name: srv-cnt
          image: 'terezabisharyan/simple-nodejs:${GITHUB_SHA::7}'
          ports:
            - containerPort: 4000
